#ifndef SRC_CRAYON_H_
#define SRC_CRAYON_H_

#define CRAYON_VERSION_MAJOR "${crayon_VERSION_MAJOR}"
#define CRAYON_VERSION_MINOR "${crayon_VERSION_MINOR}"
#define CRAYON_VERSION_PATCH "${crayon_VERSION_PATCH}"

#endif // SRC_CRAYON_H_
